// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATPUOkJ79yYIZbE7DXNuLh2qxB8S_5-OQ',
    appId: '1:64947782852:web:a0b6d6101e57ceb4cd3591',
    messagingSenderId: '64947782852',
    projectId: 'motion-955a9',
    authDomain: 'motion-955a9.firebaseapp.com',
    storageBucket: 'motion-955a9.appspot.com',
    measurementId: 'G-4BY5FS0D64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhJtZvuccMnuD5yFEeIk4RT2lsUMqPUpQ',
    appId: '1:64947782852:android:6865e2aec30feaf5cd3591',
    messagingSenderId: '64947782852',
    projectId: 'motion-955a9',
    storageBucket: 'motion-955a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKW3UzuB8EmwW9FtsHfTnbsAIttCBYU50',
    appId: '1:64947782852:ios:f209a9ac5e8931e3cd3591',
    messagingSenderId: '64947782852',
    projectId: 'motion-955a9',
    storageBucket: 'motion-955a9.appspot.com',
    iosClientId: '64947782852-poqhc34t0dcaen37ebpbvabf2s4fanlq.apps.googleusercontent.com',
    iosBundleId: 'com.motionllc.motion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKW3UzuB8EmwW9FtsHfTnbsAIttCBYU50',
    appId: '1:64947782852:ios:f209a9ac5e8931e3cd3591',
    messagingSenderId: '64947782852',
    projectId: 'motion-955a9',
    storageBucket: 'motion-955a9.appspot.com',
    iosClientId: '64947782852-poqhc34t0dcaen37ebpbvabf2s4fanlq.apps.googleusercontent.com',
    iosBundleId: 'com.motionllc.motion',
  );
}
